les10
reitsukiko/test-guru pull request #11
Opened 2022-03-28 15:35 UTC by reitsukiko

2022-03-28 16:54 UTC, BubuntuClu requested changes

2022-03-28 16:54 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies_path
нейминг `cookies_path` не очень хороший, потому что(в теории) может быть и не путь из кук

2022-03-28 16:54 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = current_user.created_tests.build(test_params)
👍

2022-03-28 16:54 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +      content_tag :p, msg, :id => key, :class => 'flash'
используй современный синтаксис, `:id => key` и тд, это устаревшее. хэшрокет в прошлом)
так же надо проверять что сообщение существует в этом ключе

2022-03-28 16:54 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирует путь на 8ой строке

2022-03-28 16:54 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирует путь на 7ой строке

2022-03-28 16:54 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email", null: false
нет уникального индекса, хотя в модели ты проверешь уникальность

2022-03-28 18:41 UTC, reitsukiko commented on app/helpers/sessions_helper.rb
> +      content_tag :p, msg, :id => key, :class => 'flash'
поняла:Dспасибо:)

2022-03-29 06:58 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    flash.each do |key, msg|
`map` было правильно. сейчас не будет работать так как надо код

2022-03-29 06:58 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +      content_tag :p, msg, class: 'flash #{key}'
`content_tag :p, msg, class: 'flash #{key}' if msg`

2022-03-29 22:12 UTC, merged